goverlay.desktop
To place in `/usr/share/applications` for system-wide integration.
There's no icon for the application yet though, the two `.ico` files seem to be generic Lazarus icons. (And a Linux icon should be in `.png` or `.svg`.)
=> Add .desktop file for packaging

goverlay.desktop
Keywords help when searching for software, see [here](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html).
tl;dr: if you search "MangoHud" or "vkBasalt" then GOverlay should appear as well.
=> add .desktop keywords

README.md, goverlay.desktop, goverlay.metainfo.xml
Based on #17.
Adds a metainfo for appstream, i.e. makes it searchable by GNOME Software, KDE Discover etc. I created it with https://www.freedesktop.org/software/appstream/metainfocreator, I've chosen the FSF All Permissive License for the metainfo (doesn't require any copyright notice) and GPL v3 or later in SPDX >=3.0 style.
Note that I included the screenshots, if you change them you should change them in the metainfo file as well.
Btw it's also possible to add a release history to the metainfo, here is an example metainfo file that does this: https://github.com/cvfosammmm/Setzer/blob/master/data/org.cvfosammmm.Setzer.appdata.xml
=> add appstream metainfo

README.md, goverlay.desktop
While it probably is very true that this will only be used on Linux, nothing prevents users from compiling this (and/or MangoHud, vkBasalt) on BSDs etc.
=> don't use Linux in description

Makefile, data/goverlay.1
While packaging GOverlay for Debian I noticed two things:
- every file is executable (which is really bad)
- there should be a man page (every file in /usr/bin should have one)
So this fixes it. To preview the man page you can run `man -l data/goverlay.1`.
=> file permissions and man page

goverlay.lpi
Currently, goverlay doesn't have position independent code (short PIC or PIE, https://en.wikipedia.org/wiki/Position-independent_code). This is actually creates a warning when building this for Debian, since PIEs are required for Address Space Layout Randomization: https://lintian.debian.org/tags/hardening-no-pie.html
Pascal supports this by adding `-fPIC` or `-Cg` to the compile arguments: https://www.freepascal.org/docs-html/current/user/usersu15.html#x38-450005.1.4
They say it's only needed for libraries since it can theoretically hurt performance, but Debian disagrees and I do as well. I didn't notice any performance regression anyway.
=> make executable position independent

README.md
AUR packages can't be installed with `pacman`.
=> Correct Arch instructions

data/goverlay.desktop
While browsing through my applications menu I noticed GOverlay is only shown in the "Graphics" category, but I think it should be shown in the "Games" category as well.
=> add category "Gaming" to .desktop file

Makefile
For example the AUR package needs to build the `--lazarusdir=/usr/lib/lazarus`, so it is a good idea to implement that additional build options can be set with make.
/cc @yochananmarqos
=> add optional build options to Makefile

Makefile
This basically tells make which files are responsible for building the `goverlay` file. If any of those changes, running `make` will automatically regenerate `goverlay`, if they don't change make won't.
It's not really necessary here, it could also just be a phony target (i. e. always run the code).
=> make make aware of code changes

README.md
Folks were complaining about installing 1.6GB of Lazarus and dependencies, so I gave in and made a binary AUR package.
=> Update README.md with new binary AUR package

goverlay.lpi
@benjamimgois I added an optional release mode, can you download the new lpi and test it as well? It enables some performance and security features, but isn't viable for debugging.
Using lazbuild `lazbuild -B ./goverlay.lpi --bm=Release`,
using make `LAZBUILDOPTS="--bm=Release" make`.
@akien-mga @yochananmarqos might be interesting for you as maintainers as well.
=> add a release mode

Makefile
This will enable the Release mode from #64 by default when building with make. Usually this isn't really wished since when developing one doesn't want the Release mode, but since development is done via Lazarus and make is basically only used for the installation, it's not a problem.
=> enable Release mode by default

install_ubuntu.sh
Building vkBasalt requires spirv-headers. 
And of course, Qt bindings for pascal.
Install script wasn't working for me, this should fix it.
=> Satisfy deps for ubuntu build

overlayunit.pas
There was a typo in the notification, in where instead of "deactivated"
it notified "desactivated". This PR fixes it.
=> Fixed typo.

overlayunit.pas
Use the `which` command to check if `replay-sorcery` is installed, since not all distros will install it to `/usr/bin/replay-sorcery`.
=> find replay-sorcery in PATH using which command

overlayunit.pas
This commit updates the previews so `vkcube` & `glxgears` are not wrapped with `mangohud` when `mangohud` is not installed.
=> support running previews without MangoHud installed

README.md
Looks like this project is packaged in OpenSUSE tumbleweed officially and Leap 15.2 via a experimental repo, so adding installation instructions to the README.
=> Add instructions for OpenSUSE installation

README.md, start_goverlay.sh
This PR makes the start script executable (to omit the `chmod +x`) and force it to use the local binary (`./goverlay` instead of `goverlay`).
I also updated the readme to for this and replaced the wayland section with an install section.
=> Update README and start script

.gitignore, Makefile
This fixes the a missing `chmod +x` for `start_goverlay.sh`, sorry for forgetting^^
As a goodie I added a `make tarball` target, you can use it to automatically create the tarball for the release including the binary and the start script. You only need to add the version via an environment variable, e.g. `env VERSION=0_7_1 make tarball`.
=> chmod fix + tarball target

Makefile, start_goverlay.sh
Can be created from `data/goverlay.sh.in` by either running `make` or `make start_goverlay.sh`.
=> Remove start_script.sh again

README.md
This PR fixes the readme file by updating the dead link to the Lazarus repo in the prerequisites sub-section of the source section.
Alternatives to the [gitlab link](https://gitlab.com/freepascal.org/lazarus/lazarus) that is included in the PR could be:
- https://github.com/fpc/Lazarus (The github mirror)
- https://www.lazarus-ide.org/ (The Lazarus website)
=> Fix link to Lazarus
